concrete = [
    {
        "label": "Concrete 50 MPa - GGBS",
        "value": "50_ggbs",
        "gb_label": "Concrete 50 MPa - GGBS  50%",
        "gb": 260.00,
        "epic_label": "Concrete 50 MPa - GGBS",
        "epic": 492.00,
        "ice_label": "Concrete 50 MPa - GGBS 50%",
        "ice": 171.819,
    },
    {
        "label": "Concrete 50 MPa - Fly Ash",
        "value": "50_fa",
        "gb_label": "Concrete 50 MPa - Fly Ash 50%",
        "gb": 363.00,
        "epic_label": "Concrete 50 MPa - Fly Ash",
        "epic": 467.00,
        "ice_label": "Concrete 50 MPa - Fly Ash 50%",
        "ice": 293.457,
    },
    {
        "label": "Concrete 50 MPa",
        "value": "50_mpa",
        "gb_label": "Concrete 50 MPa",
        "gb": 643.00,
        "epic_label": "Concrete 50 MPa",
        "epic": 600.00,
        "ice_label": "Concrete 50 MPa",
        "ice": 413.4943,
    },
    {
        "label": "Concrete 40 MPa - GGBS",
        "value": "40_ggbs",
        "gb_label": "Concrete 40 MPa - GGBS  50%",
        "gb": 328.00,
        "epic_label": "Concrete 40 MPa - GGBS",
        "epic": 392.00,
        "ice_label": "Concrete 40 Mpa - GGBS 50%",
        "ice": 212.2368194884,
    },
    {
        "label": "Concrete 40 MPa - Fly Ash",
        "value": "40_fa",
        "gb_label": "Concrete 40 MPa - Fly Ash  50%",
        "gb": 310.00,
        "epic_label": "Concrete 40 MPa - Fly Ash",
        "epic": 373.00,
        "ice_label": "Concrete 40 Mpa - Fly Ash 50%",
        "ice": 259.2980961123,
    },
    {
        "label": "Concrete 40 MPa",
        "value": "40_mpa",
        "gb_label": "Concrete 40 MPa",
        "gb": 555.00,
        "epic_label": "Concrete 40 MPa",
        "epic": 497.00,
        "ice_label": "Concrete 40 MPa",
        "ice": 386.098,
    },
    {
        "label": "Concrete 32 MPa - GGBS",
        "value": "32_ggbs",
        "gb_label": "Concrete 40 MPa - GGBS 50%",
        "gb": 288.00,
        "epic_label": "Concrete 40 MPa - GGBS%",
        "epic": 331.00,
        "ice_label": "Concrete 40 MPa - GGBS 50%",
        "ice": 172.0060314645,
    },
    {
        "label": "Concrete 32 MPa - Fly Ash",
        "value": "32_fa",
        "gb_label": "Concrete 32 MPa - Fly Ash 50%",
        "gb": 273.00,
        "epic_label": "Concrete 32 MPa - Fly Ash",
        "epic": 314.00,
        "ice_label": "Concrete 32 MPa - Fly Ash 50%",
        "ice": 221.464679076147,
    },
    {
        "label": "Concrete 32 MPa",
        "value": "32_mpa",
        "gb_label": "Concrete 32 MPa",
        "gb": 481.00,
        "epic_label": "Concrete 32 MPa",
        "epic": 416.00,
        "ice_label": "Concrete 32 MPa",
        "ice": 308.5726,
    },
]


rebar = [
    {
        "label": "Steel Reinforment Bar",
        "value": "rebar",
        "gb_label": "Over 65% Recycled Content",
        "gb": 1.733,
        "epic_label": "Steel reinforcement bar ",
        "epic": 2.9,
        "ice_label": "Steel Rebar recycled ",
        "ice": 1.99,
    },
]

steel = [
    {
        "label": "Steel Universal Section",
        "value": "steel_section",
        "gb_label": "Steel Universal Section",
        "gb": 2.9,
        "epic_label": "Steel Structural Steel Section",
        "epic": 3.88,
        "ice_label": "Steel Rebar recycled ",
        "ice": 1.55,
    },
    {
        "label": "Steel Hollow Section",
        "value": "steel_hollow",
        "gb_label": "Steel Hollow Section",
        "gb": 4.6,
        "epic_label": "Steel Structural Steel Section",
        "epic": 4.6,
        "ice_label": "Steel Rebar recycled ",
        "ice": 1.55,
    },
]

timber = [
    {
        "label": "Timber CLT",
        "value": "clt",
        "gb_label": "Cross Laminated Timber (CLT)",
        "gb": 645,
        "epic_label": "Cross Laminated Timber (CLT)",
        "epic": 645,
        "ice_label": "Timber CLT",
        "ice": 0.44,
    },
    {
        "label": "Timber Glu-Lam",
        "value": "glu_lam",
        "gb_label": "Glue Laminated Timber (Glu-Lam)",
        "gb": 718,
        "epic_label": "Glue Laminated Timber (Glu-Lam)",
        "epic": 1718,
        "ice_label": "Timber Glulam",
        "ice": 0.51,
    },
    {
        "label": "Timber Glu-Lam",
        "value": "glulam",
        "gb_label": "Glue Laminated Timber (Glu-Lam)",
        "gb": 718,
        "epic_label": "Glue Laminated Timber (Glu-Lam)",
        "epic": 1718,
        "ice_label": "Timber Glulam",
        "ice": 0.51,
    },
    {
        "label": "Timber LVL",
        "value": "lvl",
        "gb_label": "Laminated Veneer Lumber (LVL)",
        "gb": 590,
        "epic_label": "Laminated Veneer Lumber (LVL)",
        "epic": 1059,
        "ice_label": "Timber Glulam",
        "ice": 0.39,
    },
]
