concrete = [
    {
        "label": "Concrete 50 MPa - GGBS",
        "value": "50_ggbs",
        "epic_label": "Concrete 50 MPa - GGBS",
        "epic": 492.00,
        "ice_label": "Concrete 50 MPa - GGBS 50%",
        "ice": 171.819,
        "color": "#064789",
    },
    {
        "label": "Concrete 50 MPa - Fly Ash",
        "value": "50_fa",
        "epic_label": "Concrete 50 MPa - Fly Ash",
        "epic": 467.00,
        "ice_label": "Concrete 50 MPa - Fly Ash 50%",
        "ice": 293.457,
        "color": "#0866C4",
    },
    {
        "label": "Concrete 50 MPa",
        "value": "50_mpa",
        "epic_label": "Concrete 50 MPa",
        "epic": 600.00,
        "ice_label": "Concrete 50 MPa",
        "ice": 413.4943,
        "color": "#0A7AEB",
    },
    {
        "label": "Concrete 40 MPa - GGBS",
        "value": "40_ggbs",
        "epic_label": "Concrete 40 MPa - GGBS",
        "epic": 392.00,
        "ice_label": "Concrete 40 Mpa - GGBS 50%",
        "ice": 212.2368194884,
        "color": "#288FF6",
    },
    {
        "label": "Concrete 40 MPa - Fly Ash",
        "value": "40_fa",
        "epic_label": "Concrete 40 MPa - Fly Ash",
        "epic": 373.00,
        "ice_label": "Concrete 40 Mpa - Fly Ash 50%",
        "ice": 259.2980961123,
        "color": "#4FA3F8",
    },
    {
        "label": "Concrete 40 MPa",
        "value": "40_mpa",
        "epic_label": "Concrete 40 MPa",
        "epic": 497.00,
        "ice_label": "Concrete 40 MPa",
        "ice": 386.098,
        "color": "#5d9bd9",
    },
    {
        "label": "Concrete 32 MPa - GGBS",
        "value": "32_ggbs",
        "epic_label": "Concrete 32 MPa - GGBS%",
        "epic": 331.00,
        "ice_label": "Concrete 32 MPa - GGBS 50%",
        "ice": 172.0060314645,
        "color": "#9DCCFB",
    },
    {
        "label": "Concrete 32 MPa - Fly Ash",
        "value": "32_fa",
        "epic_label": "Concrete 32 MPa - Fly Ash",
        "epic": 314.00,
        "ice_label": "Concrete 32 MPa - Fly Ash 50%",
        "ice": 221.464679076147,
        "color": "#76B8F9",
    },
    {
        "label": "Concrete 32 MPa",
        "value": "32_mpa",
        "epic_label": "Concrete 32 MPa",
        "epic": 416.00,
        "ice_label": "Concrete 32 MPa",
        "ice": 308.5726,
        "color": "#C4E0FD",
    },
]


rebar = [
    {
        "label": "Steel Reinforment Bar",
        "value": "rebar",
        "epic_label": "Steel reinforcement bar ",
        "epic": 2.9,
        "ice_label": "Steel Rebar recycled ",
        "ice": 1.99,
        "color": "#F8CC0D",
    },
]

steel = [
    {
        "label": "Steel Universal Section",
        "value": "steel_section",
        "epic_label": "Steel Structural Steel Section",
        "epic": 3.88,
        "ice_label": "Steel Structural Steel Section",
        "ice": 1.55,
        "color": "#FB3640",
    },
    {
        "label": "Steel Hollow Section",
        "value": "steel_hollow",
        "epic_label": "Steel Structural Steel Section",
        "epic": 4.6,
        "ice_label": "Steel Section Structural",
        "ice": 1.55,
        "color": "#FEC3C6",
    },
]

timber = [
    {
        "label": "Timber CLT",
        "value": "clt",
        "epic_label": "Cross Laminated Timber (CLT)",
        "epic": 645,
        "ice_label": "Timber CLT",
        "ice": 0.44,
        "color": "#35A746",
    },
    {
        "label": "Timber Glu-Lam",
        "value": "glulam",
        "epic_label": "Glue Laminated Timber (Glu-Lam)",
        "epic": 1718,
        "ice_label": "Timber Glulam",
        "ice": 0.51,
        "color": "#64CE74",
    },
    {
        "label": "Timber LVL",
        "value": "lvl",
        "epic_label": "Laminated Veneer Lumber (LVL)",
        "epic": 1059,
        "ice_label": "Timber Glulam",
        "ice": 0.39,
        "color": "#A2E2AC",
    },
]
